name: release

on:
  push:
    branches: [deploy]
    tags: [v*]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Generate sdist
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        go mod vendor
        tar czf portage-exporter-${VERSION}.tar.gz --transform "s,^,portage-exporter-${VERSION}/," *

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: portage-exporter-*.tar.gz
        fail_on_unmatched_files: true
        draft: true
